/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Dialog;

import java.awt.Desktop;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

public class DlgBuscar extends javax.swing.JDialog {
    
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
           return false;
        }
    }; 
    
    public DlgBuscar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch(Exception ex) {}
        
        initComponents();
        tblTablas.setModel(model);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTablas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbColumnas = new javax.swing.JComboBox<>();
        cmbOperadores = new javax.swing.JComboBox<>();
        txtFiltro = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        radContiene = new javax.swing.JRadioButton();
        radBusquedaExacta = new javax.swing.JRadioButton();
        btnAyuda = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tblTablas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablas);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Buscar en...");

        cmbTablas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbTablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes", "Estadísticas de clientes", "Artículos", "Cabecera de facturas", "Línea de facturas", "Total de facturas" }));
        cmbTablas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTablasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTablas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Donde...");

        cmbColumnas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbColumnas.setMaximumRowCount(10);
        cmbColumnas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dnicif", "nombrecli" }));
        cmbColumnas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbColumnasItemStateChanged(evt);
            }
        });

        cmbOperadores.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbOperadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "LIKE", "NOT LIKE" }));

        txtFiltro.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbOperadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Expresiones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        buttonGroup1.add(radContiene);
        radContiene.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        radContiene.setText("Contiene...");

        buttonGroup1.add(radBusquedaExacta);
        radBusquedaExacta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        radBusquedaExacta.setSelected(true);
        radBusquedaExacta.setText("Búsqueda exacta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBusquedaExacta)
                    .addComponent(radContiene))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(radBusquedaExacta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radContiene)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAyuda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOK)
                    .addComponent(btnAyuda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        txtFiltro.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("README.pdf");
                Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error", "No se puede abrir el documento.", JOptionPane.ERROR);
            }
        }   
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void cmbColumnasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbColumnasItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) { 
            
            cmbOperadores.removeAllItems();

            if ("dnicif".equals(cmbColumnas.getSelectedItem().toString()) ||
                "nombrecli".equals(cmbColumnas.getSelectedItem().toString()) || 
                "referencia".equals(cmbColumnas.getSelectedItem().toString()) || 
                "descripcion".equals(cmbColumnas.getSelectedItem().toString()) || 
                "mesNom".equals(cmbColumnas.getSelectedItem().toString())) {
                
                cmbOperadores.addItem("=");
                cmbOperadores.addItem("LIKE");
                cmbOperadores.addItem("NOT LIKE");

            } else if ("precio".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "porciva".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "stock".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "anio".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "mesNum".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "sumaBase".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "sumaDtos".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "sumaIva".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "sumaTotales".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "numfac".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "fechafac".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "lineafac".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "cantidad".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "dtolinea".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "ivalinea".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "baseimp".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "impDto".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "impIva".equals(cmbColumnas.getSelectedItem().toString()) || 
                        "totalfac".equals(cmbColumnas.getSelectedItem().toString())) {
                cmbOperadores.addItem("=");
                cmbOperadores.addItem("<");
                cmbOperadores.addItem("<=");
                cmbOperadores.addItem(">");
                cmbOperadores.addItem(">=");
            }
        }
    }//GEN-LAST:event_cmbColumnasItemStateChanged

    private void cmbTablasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTablasItemStateChanged
        cmbColumnas.removeAllItems();
        
        if ("Clientes".equals(cmbTablas.getSelectedItem().toString())) {
            cmbColumnas.addItem("dnicif");
            cmbColumnas.addItem("nombrecli");
        } else if ("Artículos".equals(cmbTablas.getSelectedItem().toString())) {
            cmbColumnas.addItem("referencia");
            cmbColumnas.addItem("descripcion");
            cmbColumnas.addItem("precio");
            cmbColumnas.addItem("porciva");
            cmbColumnas.addItem("stock");
        } else if ("Línea de facturas".equals(cmbTablas.getSelectedItem().toString())) {
            cmbColumnas.addItem("numfac");
            cmbColumnas.addItem("lineafac");
            cmbColumnas.addItem("referencia");
            cmbColumnas.addItem("cantidad");
            cmbColumnas.addItem("precio");
            cmbColumnas.addItem("dtolinea");
            cmbColumnas.addItem("ivalinea");
        } else if ("Cabecera de facturas".equals(cmbTablas.getSelectedItem().toString())) {
            cmbColumnas.addItem("numfac");
            cmbColumnas.addItem("fechafac");
            cmbColumnas.addItem("dnicif");
        } else if ("Total de facturas".equals(cmbTablas.getSelectedItem().toString())) {
            cmbColumnas.addItem("numfac");
            cmbColumnas.addItem("baseimp");
            cmbColumnas.addItem("impDto");
            cmbColumnas.addItem("impIva");
            cmbColumnas.addItem("totalfac");
        } else if ("Estadísticas de clientes".equals(cmbTablas.getSelectedItem().toString())) {
            cmbColumnas.addItem("anio");
            cmbColumnas.addItem("mesNum");
            cmbColumnas.addItem("mesNom");
            cmbColumnas.addItem("dnicif");
            cmbColumnas.addItem("sumaBase");
            cmbColumnas.addItem("sumaDtos");
            cmbColumnas.addItem("sumaIva");
            cmbColumnas.addItem("sumaTotales");
        } 
        cmbColumnasItemStateChanged(evt);
    }//GEN-LAST:event_cmbTablasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgBuscar dialog = new DlgBuscar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cmbColumnas;
    public javax.swing.JComboBox<String> cmbOperadores;
    public javax.swing.JComboBox<String> cmbTablas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JRadioButton radBusquedaExacta;
    public javax.swing.JRadioButton radContiene;
    private javax.swing.JTable tblTablas;
    public javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
